### ISSUE TITLE
nginx config?

### ISSUE THREAD

**Issue by emjayess** [aheinze/cockpit#19]
Wondering if anyone has a working nginx config for cockpit... I'm having a little trouble. I do actually get the install page back with a success message, but then I wind up at a 404 upon attempt to reach login...

e.g. ```/manage/index.php/auth/login```

(cockpit itself lives in the ```/manage``` subfolder within the otherwise static site)

**Comment by HamGuy** [comment]
I had the same issue with the following config:

```
server {
    listen 80;
    server_name cockpit.dev;
    root /usr/share/nginx/html/cockpit;
    index index.php index.html index.htm;

    error_log /var/log/nginx/cockpit_error.log.txt;
    access_log /var/log/nginx/cockpit_access.log.txt;
    
    # Add additional types
    include mime.types;

    location / {
        index index.php index.html index.htm;
    }

    # Change "cockpit" to the folder name containing cockpit files.
    location /cockpit {
        try_files $uri $uri/ /cockpit/index.php;
        index index.php index.html index.htm;
    }

    location ~ \.php(/|\?|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param COCKPIT_URL_REWRITE On;
        include fastcgi_params;
    }

    location ~ .sqlite$ {
        deny all;
    }
}
```

And the file structure is 
```
/www(root)/cockpit/*
```

**Comment by aheinze** [comment]
nginx sample config available here: https://github.com/aheinze/cockpit-docs/blob/master/tutorials/nginx.md

**Comment by lhardie** [comment]
Just in case anyone has issues still ( I did today ), the following nginx config worked for me:

`server {
    listen 80;
    server_name _ myCockpit.com;
    root /var/www/html/cockpit-master;
    index index.php;

    location / {
      try_files $uri $uri/ /index.php;
    }

    access_log  /var/log/nginx/cockpit.access.log;
    error_log   /var/log/nginx/cockpit.error.log;

    # Deny direct access to .sqlite
    location ~ .sqlite$ {
        deny all;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param COCKPIT_URL_REWRITE On;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    location ~ /\.ht {
        deny all;
    }
}`

**Comment by Tummerhore** [comment]
Thank you, lhardie. You're a life saver! I was trying it for the whole day and was always running into the same problem.
Cockpit's documentation strongly needs more detailed installation instructions in this regard.

What I find rather strange is the fact, that cockpit now works even if use my old nginx.config with which it didn't work the first time...
