### ISSUE TITLE
"Insert Media" seems to insert images with relative path that breaks when rendered

### ISSUE THREAD

**Issue by scogle** [aheinze/cockpit#217]
It seems like the "insert media" action in the insert menu, though appearing to work nicely in the WYSIWYG editor, inserts an image with a  relative `src` that's obviously doesn't point to anything when the page renders.  What's more, it seems like when I try to fix the problem by manually adding a leading slash (in the source code or in the edit image dialog) it strips them and I'm back to the same issue.

**Comment by charkes** [comment]
newgeekorder's comment is an enhancement.  scogle's comment is a bug I'm also experiencing.  I use "Insert media", pick a photo I've uploaded using the Mediamanager, and it inserts:

```html
<p><img class="auto-size" src="../../../../up/san-francisco.jpg" alt="" /></p>
```

**Comment by charkes** [comment]
It looks to be TinyMCE's doing.  Cockpit's code is correctly changing site: to the base path but then the editor is making it a relative URL.

Solution: add "relative_urls: false" to TinyMCE's init options.

http://www.tinymce.com/wiki.php/Configuration:relative_urls
