### ISSUE TITLE
fatal error encountered

### ISSUE THREAD

**Issue by designermonkey** [aheinze/cockpit#234]
I'm coming across a fatal error with the `findOne` function of `/vendor/MongoHybrid/Mongo.php`, stating that the findOne call within the function is passed null, when expecting an array/object.

I've tried changing the default in the function params to an empty array, which allows login to continue, but every admin page after that throws a 500 error.

This is the function

```php
    public function findOne($collection, $filter = [], $projection = null) {

        if(isset($filter["_id"]) && is_string($filter["_id"])) $filter["_id"] = new \MongoId($filter["_id"]);

        $doc =  $this->getCollection($collection)->findOne($filter, $projection);

        if(isset($doc["_id"])) $doc["_id"] = (string) $doc["_id"];

        return $doc;
    }
```

This is the change I made

```php
    public function findOne($collection, $filter = [], $projection = []) {

        if(isset($filter["_id"]) && is_string($filter["_id"])) $filter["_id"] = new \MongoId($filter["_id"]);

        $doc =  $this->getCollection($collection)->findOne($filter, $projection);

        if(isset($doc["_id"])) $doc["_id"] = (string) $doc["_id"];

        return $doc;
    }
```

So, I can either log in and get a 500 error, or get fatal errors at boot up of the app :(

Any ideas?

**Comment by aheinze** [comment]
should be fixed now.

**Comment by designermonkey** [comment]
Super, will check it out.

**Comment by designermonkey** [comment]
Works a treat, thanks.
