### ISSUE TITLE
Collection media preview breaks out of the container

### ISSUE THREAD

**Issue by zakbach** [aheinze/cockpit#243]
When adding a media item, such as video, the preview breaks out of the container as shown in the image below.

![102923](https://cloud.githubusercontent.com/assets/10362886/5591896/34250bf0-91a1-11e4-9dea-90be6f5157fd.png)

**Comment by AC10** [comment]
The video is displayed with the HTML5 element, video
It's a quick fix, the video element just need a ``` max-width ``` on ``` 100% ``` in the CSS
