### ISSUE TITLE
Not Able to Use The Assets API!

### ISSUE THREAD

**Issue by Conciliare** [aheinze/cockpit#252]
I am having some trouble with the assets API and I have tried multiple things but all it seems to do is make a blank page?

**Comment by aheinze** [comment]
hi,

do you have access to the php error log files?

**Comment by Conciliare** [comment]
Yes I do but there were no errors :/

**Comment by aheinze** [comment]
apache error log files maybe?

**Comment by Conciliare** [comment]
Nothing in there involving cockpit just some ssl issues which I fixed.

**Comment by Conciliare** [comment]
Any help here? I am so confused because of no errors or any error files, if you want I can email you all my log files or PM you!

**Comment by Conciliare** [comment]
I think I may not be using it right or I am doing something incorrectly, am I supposed to place my css and js files in the assets folder or can I link to them? or where should I put them exactly?

**Comment by florianletsch** [comment]
What exactly are you trying to do exactly? Maybe give us some lines of code and tell us which files are located in which folder.

**Comment by Conciliare** [comment]
<?php
cockpit("cockpit")->assets([
    "css/reset.css",
    "css/style.css",
    "css/font-awesome/css/font-awesome.min.css",
    "css/responsive-leyouts.css",
    "js/mainmenu/sticky.css",
    "js/mainmenu/bootstrap.min.css",
    "js/mainmenu/demo.css",
    "js/mainmenu/menu.css",
    "js/revolutionslider/css/style.css",
    "js/revolutionslider/rs-plugin/css/settings.css",
    "css/Simple-Line-Icons-Webfont/simple-line-icons.css",
    "js/flexslider/flexslider.css",
    "js/accordion/accordion.css",
    "js/tabs/assets/css/responsive-tabs.css",
    "js/tabs/assets/css/responsive-tabs2.css",
    "js/tabs/assets/css/responsive-tabs3.css"
], 'proxybite.assets' [, $cachetime=0]);
?>

**Comment by florianletsch** [comment]
Tried to "echo" that? I'm not sure, but assets() might just return the generated string

**Comment by Conciliare** [comment]
No I have not tried to echo it at all but this is what I am trying to do http://getcockpit.com/docs#!helper/assets

**Comment by andrewkdesigns** [comment]
I get a 501 error when I use the code exactly like it is in the docs page.
When I use like this:
```php
            cockpit("cockpit")->assets([
                "/app/assets/vendor/uikit/js/uikit.min.js",
                "/js/view.js",
            ], 'sla.assets', [$cachetime=0]);
```
it doesn't 501 and it puts the script on the page but its empty.
