### ISSUE TITLE
Multiple Item Region - Testimonials

### ISSUE THREAD

**Issue by samg0ddard** [aheinze/cockpit#253]
I'm trying to figure out if it's possible to have multiple region entries, for example, I want to create a region for 'Testimonials' which will have a text box for name, and a text box for the testimonial, I've got this working fine however I want to add the ability to add multiple of these in the back-end which will auto populate on the site, is this possible using Cockpit? I've been playing with Collections but can't seem to get what i'm after.

Cheers

**Comment by aheinze** [comment]
why don't you create a collection? and loop in the region template through the collection items?

**Comment by samg0ddard** [comment]
That's what i've been trying but I think i'm doing something wrong, i've attached a screenshot of my region setup, and then the collection field which pulls the region in, what am I doing wrong? When I try to add an item to the collection there's just nothing there.
![region](https://cloud.githubusercontent.com/assets/8715435/5816069/161b1274-a094-11e4-88be-a78cceee7691.png)
![collection](https://cloud.githubusercontent.com/assets/8715435/5816070/1623b244-a094-11e4-8e5e-f6b910c743a4.png)

**Comment by aheinze** [comment]
you have to think the other way.

first create a collection "Testimonials" with the needed fields e.g. name, testemonial.

then in your region "Tests" switch to the template view and add the following snippet:

```php
@foreach(collection('Testimonials')->find() as $test)
      <h3>{{ $test['name'] }}</h3>
      <p>{{ $test['testemonial'] }}</p>
@endforeach
```

then you can render the region with ```<?php region('Tests') ?> ```wherever you want.

**Comment by samg0ddard** [comment]
Ah, that makes sense!! I've tried that and i'm getting PHP errors (see attached), any ideas what i'm doing wrong? Thanks very much for the help :)
![untitled-3](https://cloud.githubusercontent.com/assets/8715435/5816532/0c35d2da-a099-11e4-9053-859ee33b1965.png)

**Comment by samg0ddard** [comment]
My bad, it's me being an idiot, that's working perfectly, thank you very much!!

**Comment by aheinze** [comment]
:+1:
