### ISSUE TITLE
Bug : slug in collection field

### ISSUE THREAD

**Issue by Chloee** [aheinze/cockpit#257]
I create a collection with a field "name" and I create items of it. After, I edit collection and I add slug option on my "name" field. If I export my JSON collection, items doesn't have slug_name. And if I create a new item and export again, my new item have a name_slug but not the others items. So I edit every items and save it to have my name_slug. 

So sorry for my english ...

**Comment by malles** [comment]
I think that is not a bug report but a feature request.
Auto-populating later added fields is solving bad architecture. Make sure your fields are done before putting data in it

**Comment by aheinze** [comment]
I fully agree with @malles . every one should have an idea about the needed data structure before entering data ... or write custom altering/miigration scripts afterwards.

**Comment by Chloee** [comment]
maybe... so add an option "update all entries" after editing collection form ?
