### ISSUE TITLE
Change mime type

### ISSUE THREAD

**Issue by tgrandsire** [aheinze/cockpit#258]
Hi,

I tried to bind a route with $app->bind() in order to have a XML file, but I don't know how to change mime type, can you help me please ?

Here my code:

$app->bind("#/sitemap.xml$#", function() use($app) {
    return $app->render('sitemap.xml.twig');
});

**Comment by tgrandsire** [comment]
I tried xith header("Content-type: text/xml; charset=utf-8"), but response is still 'text/html'.

**Comment by aheinze** [comment]
you don't need ```use ($app)```, $this within a route callback is the actual $app. so:

```php
$app->bind("#/sitemap.xml$#", function() {
    $this->response->mime = 'xml';
    return $this->render('sitemap.xml.twig');
});
```
