### ISSUE TITLE
Lime routing not rendering

### ISSUE THREAD

**Issue by arlg** [aheinze/cockpit#259]
Hi. 
I want to une Lime router as documented here http://getcockpit.com/docs#!tutorials/simple_blog
But when a route is mathched, the template is not rendered in my page. I don't have any errors.

Here is the code i use : 

    $app = new Lime\App();
    $app->path('views', __DIR__.'/templates/pages/');
    $app->bind("*/page", function($params) use($app) {

                $items = cockpit('collections:collection', 'mycollection')->find()->toArray();

                $page = $app->path('views:page.php');

                return $app->render( $page , ['items' => $items]);
            });

**Comment by florianletsch** [comment]
Which URL are you calling to test this?

I would add an echo statement inside the function and one outside so you can check what code is actually being executed. 

The route string `"*/page"` looks like it might not be what you want. Did you maybe want to have something like `"/page/*"` or similar?

**Comment by arlg** [comment]
The url is for example "website.dev/uk/page" 
The * stands for the language id ( the website has 5 different langs ).

The echo inside the function is working so the route is matched.
I think im missing something but I don't know what .. !

**Comment by aheinze** [comment]
maybe also check, what ```$app->render( $page , ['items' => $items]);``` returns.

**Comment by arlg** [comment]
$app->render( $page , ['items' => $items]); returns the template content. I can also print_r() $items content

**Comment by arlg** [comment]
Do i need to "echo" the result of the ->render method in order to display it on the page ?

**Comment by florianletsch** [comment]
No you shouldn't need to do that. Are you sure you have `$app->run();` at the end of your script (after you're done binding everything)?

**Comment by arlg** [comment]
Yep i have it. Here is the full page for my index.php

    <?php 
    error_reporting(E_ALL);
    ini_set("display_errors", 1);
    require_once("admin/bootstrap.php"); // Includes Cockpit

    // LIME init

    $app = new Lime\App();
    $app->path('views', __DIR__.'/templates/pages/');
    ?>

    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>Website</title>
            <meta name="description" content="">
        </head>
        <body>
            <div class="content">
            
            <?php

                $app->bind("*/page", function($params) use($app) {

                    $items = cockpit('collections:collection', 'mycollection')->find()->toArray();

                    $page = $app->path('views:page.php');

                    return $app->render( $page , ['items' => $items]);
                 });

            

                $app->bind("/", function()  use($app)  {
                    return "Hello World!";
                });

            


                $app->run();
            ?>

        </div>
    </body>
</html>


And my .htaccess : http://pastebin.com/hbYf6AaR ( Lines doesn't appear here )

**Comment by florianletsch** [comment]
You should move your markup out of the controller code. It will be a problem when your browser starts sending a reply before you run the $app or even register your routes. 


Instead, do this: Have your index.php do all the init stuff, bind routes and run the $app. Put your markup in a separate file, i.e. `view/layout.view.php`. Then when initializing Lime, you can set that layout:
`$app->layout = "views/layout.view.php";`

Inside of the layout, make sure to have the following line: `<?php echo $content_for_layout;?>`

That's how the blog tutorial explains it as well (minus the $app->layout stuff).

**Comment by arlg** [comment]
Oh ok, I did not got that part on the tutorial... It works now ! 
Maybe It would be good to add a .zip with files on the tutorial page, so that people can download it and see how it works with real files ?
( I can help with that now I understood how it works )

Thanks for the help anyway :)

**Comment by aheinze** [comment]
@florianletsch merci!
