### ISSUE TITLE
Switch to MongoDB not working.

### ISSUE THREAD

**Issue by telekommander** [aheinze/cockpit#260]
Having trouble to switch to MongoDB.
MongoDB is up and running on localhost. // Testet.

Not sure is it a wrong localhost config or is there something wrong in cockpit.

The config file looks like the example on documention page.
http://getcockpit.com/docs#!getting_started/configuration

But get an error ...

![screenshot_2015-01-27_001](https://cloud.githubusercontent.com/assets/1859497/5922920/aeb1eef2-a64f-11e4-9ef5-0e00a022077e.png)

**Comment by aheinze** [comment]
should be fixed now with this commit: https://github.com/aheinze/cockpit/commit/5ffa728bfbce50ce415b2820726278e59385eec8 . thank you for reporting.
