### ISSUE TITLE
How to get all collections using api

### ISSUE THREAD

**Issue by mr6volt** [aheinze/cockpit#267]
The current API docs only who how to get items from a specific collection. How would we go about pulling ALL of the collections and their related entries?

I'm asking this, because i'd like to load an entry based on it's slug in a more generic way. Right now i have to hardcode the collection slug.

**Comment by aheinze** [comment]
First get a collection list and get the entries as needed.

```
$collections = cockpit('collections')->collections();

foreach($collections as $name => $collection) {
    $entries = $collection->find();
}

```

**Comment by mr6volt** [comment]
Thanks, it works!
