### ISSUE TITLE
Blank page? Not sure what's going on.

### ISSUE THREAD

**Issue by daltonsutton** [aheinze/cockpit#268]
I downloaded Cockpit for the first time today. Go it installed but I'm lost now.

This is what I'm getting on my dashboard.
![screen shot 2015-02-02 at 8 03 01 pm](https://cloud.githubusercontent.com/assets/3005706/6012481/8daa0e58-ab16-11e4-83fb-55ff729afa1e.png)

...and a blank page on every page. 
![screen shot 2015-02-02 at 8 03 57 pm](https://cloud.githubusercontent.com/assets/3005706/6012493/b8a9dbf6-ab16-11e4-8578-8044967b3d32.png)

I viewed the source of the pages and everything looks there. All the HTML with forms and everything, but nothing is showing... This leads me to believe it's a javascript problem? I made sure my javascript was enabled on my browser and I'm not having a problem with javascript on any other site. 

Looking for some help on this. Thanks in advance!

**Comment by daltonsutton** [comment]
Further looking into this, it's something to do with Firefox. It works fine in other browsers.

**Comment by aheinze** [comment]
this is strange. do you have any special firefox plugin/extension installed?

**Comment by daltonsutton** [comment]
None. Just the default Firefox. Even updated it.

**Comment by AC10** [comment]
I'm using Firefox, and I haven't encountered any problems at all

**Comment by aheinze** [comment]
@daltonsutton could you resolve it?

**Comment by jobrodesign** [comment]
I saw this issue with chrome, but it was down to an extension (the feedly mini button actually) that caused it.  Is anything showing up in the Web Console?

**Comment by daltonsutton** [comment]
@aheinze I have not. I've just been going at in in another browser. I would like to figure it out in Firefox though. My comfort zone. @jobrodesign, I don't have any extensions enabled and my Web Console hasn't had anything pop out to me that would make it seem like there's a problem.

**Comment by daltonsutton** [comment]
As for my Web Console, I haven't had much experience with it. But this is what came up.

![screen shot 2015-02-03 at 12 48 56 pm](https://cloud.githubusercontent.com/assets/3005706/6025787/253dcae8-aba3-11e4-8e1b-d5eb63820709.png)

I'm not exactly sure if something in here could be causing the problem.

**Comment by aheinze** [comment]
maybe your dom storage is disabled.

Type “about:config” in your address bar and hit enter to view your internal browser settings. Scroll down to „dom.storage.enabled“, right click on it and hit „Toggle“ to enable the DOM Storage.

**Comment by daltonsutton** [comment]
Works perfectly! I really appreciate you helping me out, thanks man!

**Comment by aheinze** [comment]
:+1:
