### ISSUE TITLE
Update cockpit or backup site from cockpit administration

### ISSUE THREAD

**Issue by Chloee** [aheinze/cockpit#270]
Great new version, thanks ! So I tried to update directly from interface ...
Update or backup feature doesn't work : "Uups something went wrong".
I tried on my local wamp server. So I updated manually by downloading the new version.

All backups are corrupt .zip. When I open zip folder, it is empty.

**Comment by aheinze** [comment]
Sorry, but I can't confirm this issue....maybe there's something wrong with the file permissions?

**Comment by florianletsch** [comment]
How did you do the manual update? Did you overwrite the database file by accident? That would explain the empty backup zips.
