### ISSUE TITLE
[security] full public access to all files, incl. databases !?

### ISSUE THREAD

**Issue by panique** [aheinze/cockpit#273]
Hi, 

I just want to add: The install guideline does not say anything about mod_rewrite or about "activating" .htaccess ! So, by default, the full project tree is fully accessable, including the database files unless you have mod_rewrite properly activated and allowed .htaccess files to overwrite the apache configs. An attacker can easily download the full database.

Maybe I'm missing something totally here, please correct me if I'm wrong, but this should be noted in the install guideline, otherwise lots of people are publishing their databases public on the web :) !

**Comment by aheinze** [comment]
hi,

I have to say a valid point. I'll add a section to the docs to adress that. 
btw. you're able to define a custom data folder outside the webroot or switch to mongodb. but as you mentioned, the documentation needs to catch up on this topic.

thanks and gute nacht!

**Comment by panique** [comment]
@aheinze He Artur, I had issues like that in my open-source projects too and received of lot of bashing for that :) so maybe I can help you here. Personally I think cockpit will become one of the most used php-CMSs in the world, so it makes sense to improve the project imo.

Possible workarounds to increase security:

1. We could write a short section (like you said) that describes this problem and gives some simple and some not-so-simple solutions, like
 - moving the db files to a folder outside of the public accessible folder
 - or a guideline on how to activate (and test) mod rewrite
2. Maybe the installer could also test this and give some instructions how to do this.
3. Side-effect: Also .git "folder" is accessable / downloadable
4. Under círcumstances directly called .php files can show critical information or error messages or stuff like that.
5. There are other issues possible too (I just heard that from an infosec guy posting on my github repos), like directly accessable non-.php-file temp/swap copies of .php files, like `config.php~`, which might be a (undeleted) text editor's temp file from editing config.php. As it's not a php file it can be downloaded and will not be parsed, so it's basically a text file holding the configs (passwords) in plain text.

But, by the way: Problems like this exist in nearly every CMS and most PHP applications, even older versions of the major frameworks have these problems, so we are definitly not alone here :) Sorry, I hope i have not ruined your day. Oh damn I feel bad now.

**Comment by panique** [comment]
Maybe we should delete this ticket to prevent people from mis-using this information ? Hmm...Does somebody know if GitHub has a private-ticket function or so ?

**Comment by arysom** [comment]
maybe simple htacces could do the job

    RewriteEngine On
    RewriteCond %{REQUEST_URI} (.*).db [NC] 
    RewriteRule ^(.*)$ 404.html [R=404,L]

and index html file inside every directory, to prevent listing

**Comment by aheinze** [comment]
@arysom sqlite files are already secured via .htaccess ... it is about the case when htacces overrides are not enabled.

**Comment by arysom** [comment]
youre right, ive read without understanding

**Comment by aheinze** [comment]
data security section added to the docs.
