### ISSUE TITLE
Datastore findOne() always returns NULL

### ISSUE THREAD

**Issue by oliverhermanni** [aheinze/cockpit#274]
I tried to use a datastore for registering users to a frontend. Saving works, but when I try to find a single element with findOne, it always returns NULL - although the element and the filtered values exist.

**Comment by florianletsch** [comment]
Please give us some code that you're using. :)

**Comment by oliverhermanni** [comment]
Ah, of course. :)

This is how I save the user:

    $user = [
        'email'             => filter_input(INPUT_POST, 'email', FILTER_SANITIZE_EMAIL),
        'password'          => filter_input(INPUT_POST, 'password', FILTER_SANITIZE_STRING),
        'salt'              => $salt,
        'active'            => false,
        'activationcode'    => md5($salt)
    ];
    cockpit('datastore:save_entry', 'users', $user);

If I want to retrieve the same user with

    $user = cockpit('datastore:findOne', 'users', [
        'filter' => ['email' => 'test@test.de']
    ]);

I get NULL.

But it's saved in the datastore as

    {
        "email": "test@test.de",
        "password": "329c65[...]",
        "salt": "9d2274a[...]",
        "active": false,
        "activationcode": "383741[...]",
        "modified": 1423264809,
        "created": 1423225716,
        "_id": "54d54c29b4972doc12156"
}

**Comment by aheinze** [comment]
$user = cockpit('datastore:findOne', 'users', ['email' => 'test@test.de']);

**Comment by oliverhermanni** [comment]
Ah, thanks! Then it needs to be fixed in the docs. ;) There's the additional filter array.

**Comment by aheinze** [comment]
thank you for the hint!
