### ISSUE TITLE
Region data and image paths

### ISSUE THREAD

**Issue by jsantari** [aheinze/cockpit#279]
Is there any built in way to get all the fields back as an array where you can directly access $myregion['field name']? Getting the metadata then getting the fields just gets you an array with all the fields and each field is an array. Have to manually convert it to any array to do something like $myregion['Title']. I know you can call cockpit('regions:region_field', 'Footer', 'aboutme', 'value') for each field but that seems a bit verbose and extra work.

Also, the image path inside of an html type field will not render as the path has ../../ in it which of course is wrong from root.

Likewise an image type field has an extra couple of levels in the metadata making it harder yet to extract with out more coding on the front end. Plus it also has an image path which won't work as in my case it has site:assets/images/somefile.jpg.

Seems like the back end is pretty solid but the front end api is lacking unless there are some other options I'm not aware of.

**Comment by aheinze** [comment]
I think you try to use regions not in the way they were made for. the region fields are meant to be reused in the region template.

with the region render api you render the result of the combination of template with fields. maybe a collection is more suited for what you're try to accomplish.

**Comment by jsantari** [comment]
Ok, I'm trying to use a region as the main body of the page which seems to me would be one of it's uses. I set up a simple template. I only have 3 fields in the region; Title, Body (html field) and Image which is type gallery. I've created the following template using your built in feature. I figured out how to reference my Image field path but it would be nice if insert field gave me the option to pick the path or title. However even with your built in template we have the same problem - the links to the image files are invalid.

---
<h3>
{{ $Title }}
</h3>
<p>
{{ $Body }}
</p>
@foreach($Image as $item)
  <img src="{{ $item['path'] }}">
@endforeach
---

**Comment by aheinze** [comment]
```<img src="{{ url_to($item['path']) }}">```

**Comment by jsantari** [comment]
Thanks but it didn't work. I get this in the page now. 
    <img src="">
What about the Body field, I get this there.
    <img class="auto-size" src="../../assets/images/logoQB.png" alt="">

**Comment by aheinze** [comment]
ok, this is strange. is it possible to send me the project, so I can investigate the issue?

**Comment by jsantari** [comment]
I've attached a zip of the folder.

On 2/12/2015 2:22 AM, Artur wrote:
>
> ok, this is strange. is it possible to send me the project, so I can 
> investigate the issue?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/aheinze/cockpit/issues/279#issuecomment-74033758>.
>

-- 
Jim Santarius
NCC Technology Group

**Comment by jsantari** [comment]
Any progress on this issue?

**Comment by aheinze** [comment]
sorry, didn't get anything.

**Comment by jsantari** [comment]
I replied to the email from Github with an attachment on the 12th. Should I send the email to another address?

**Comment by outflux3** [comment]
this is working for me
{{ url_to($image) }}
but 
{{ url_to($leftImage['path']) }}
causes a lexy error
