### ISSUE TITLE
Limit / paginate gallery photos

### ISSUE THREAD

**Issue by klepje** [aheinze/cockpit#286]
Hi there,

is it possible to limit the count of photos which you request from a gallery?
Like: I've 4 photos on my frontpage, and want on the click of a button, that the next 4 are loaded.
Is it possible to have requests like: 
get first 4 photos: /galleries/get/photos?start=0&limit=4
get photo 5 till 8:  /galleries/get/photos?start=4&limit=4
etc.

With kind regards

**Comment by aheinze** [comment]
sorry, this is not possible. but I would do the pagination on the client side. get the gallery once and handle the pagination via Javascript.
