### ISSUE TITLE
Upload PDFs to Cockpit CMS

### ISSUE THREAD

**Issue by Carpetfizz** [aheinze/cockpit#290]
Hello,

Is it possible to upload a PDF to a collection? If not, are there any addons that support this feature?

Thank you!

**Comment by usandfriends** [comment]
+1

**Comment by adaniello** [comment]
I don't know, but are you sure that it isn't already supported?

See at:
https://github.com/aheinze/cockpit/blob/94e907aab7caa5945afe0969b0b0ff9bd3d90bb9/assets/js/angular/directives/mediapreview.js#L38

**Comment by aheinze** [comment]
you can use a media field, and link your pdf to it.

**Comment by Carpetfizz** [comment]
Thanks guys, it's working!
