### ISSUE TITLE
Gallery through collection, adding to a region

### ISSUE THREAD

**Issue by samg0ddard** [aheinze/cockpit#292]
Hi there,

So i'm using a Collection to capture a gallery, I want to display lots of mini galleries on a page and thought this would be the easiest way. I want to output said galleries using a region and pulling it through from the Collection data. I have all the other fields working but can't get the gallery pulling through, could you help me out?

Thanks in advance!
Sam

**Comment by aheinze** [comment]
could you please post your region code?

**Comment by samg0ddard** [comment]
Hi Artur,

Heres' my region code so far:

@foreach(collection('Used Vehicles')->find() as $usedvehicles)

<div class="job-vacancy">

	<div class="col-left">
    
		<h1>{{ $usedvehicles['vehicle_name'] }}</h1>
                                
	</div>

@endforeach

I want to add the gallery below the H1 tag.

Cheers!
Sam

**Comment by aheinze** [comment]
```$usedvehicles['vehicle_gallery']``` is a name reference of a gallery as string, e.g "mycars"?

**Comment by samg0ddard** [comment]
$usedvehicles is referencing the collection, the collection has a field in it that collects a gallery if that makes sense? (see image below)

![cockpit](https://cloud.githubusercontent.com/assets/8715435/6523070/1d62a4a2-c3e4-11e4-96f4-cb303d876b29.jpg)

**Comment by aheinze** [comment]
```
@foreach($usedvehicles['gallery'] as $pic)

   <img src="{{ thumbnail_url($pic['path'], 1024, 690) }}" alt="{{ @$pic['title'] }}">

@endforeach
```

**Comment by samg0ddard** [comment]
Perfect, thanks a lot Artur.

**Comment by aheinze** [comment]
:+1:
