### ISSUE TITLE
Lime subtemplates

### ISSUE THREAD

**Issue by arlg** [aheinze/cockpit#293]
Can we import php files into a template ?
For example i have the file gallery.php loaded when my router hits /gallery , but inside i want to load another template.

**Comment by florianletsch** [comment]
When using Lexy, you can use the render directive for that and even pass data:

```
@render('views/photo.php', ['id' => 23])
```

Which is just a shorthand for the following:

```php
<?php echo $app->view($file, $args); ?>
```
