### ISSUE TITLE
Alt tags on gallery images.

### ISSUE THREAD

**Issue by Sospy** [aheinze/cockpit#300]
Hi,

I am pulling a gallery like this:

    <?php foreach(gallery(Centre) as $image): ?>
    <a class="gallery fancybox" href="<?php echo $thumbUrl = substr($image['path'], 5); ?>"><?php   thumbnail($image["path"], 150, 150) ?></a>

    <?php endforeach;?>

Is there a way to add a custom alt tag to my galleries images? Global or image specific.

Thanks,
S

**Comment by aheinze** [comment]
```php 
thumbnail($image["path"], 150, 150, ['attrs' => ['alt' =>'my custom alt'])
```

**Comment by Sospy** [comment]
Perfect, thank you!
