### ISSUE TITLE
Save entry with Cockpit.js

### ISSUE THREAD

**Issue by arlg** [aheinze/cockpit#302]
Is it possible to save an entry to a collection using Cockpit in the the frontend side ? ( with Cockpit.js ). 

There is no sign of it in the documentation. ( only Server side )

thanks

**Comment by namaless** [comment]
I need too, but for a moment (you can see the source code) is not possible, you need to load cockpit inside your project then you can use a module call for save entry: https://github.com/aheinze/cockpit-docs/blob/master/modules/collections.md#save_entry-name-data-

**Comment by arlg** [comment]
Ok im gonna call this viva Ajax. Thanks !

**Comment by namaless** [comment]
No problem if it's fixed, please close the issue.
