### ISSUE TITLE
Simplest Lime routing example not rendering

### ISSUE THREAD

**Issue by jwhscholten** [aheinze/cockpit#311]
Hi,

I'm trying to set up some basic routing using Cockpit and Lime but even the most basic example is giving me a blank screen and no errors. Any thoughts on what might be the issue?
Cockpit works fine on my server (and passes the requirements).

```php
<?php 

    include_once('beheer/bootstrap.php');

    error_reporting(E_ALL);
    ini_set('display_errors', 1);

    $app = new Lime\App();

    $app->bind("/", function() {
        return "Hello World!";
    });

    $app->run();

    var_dump($app);

?>
```

.htaccess
http://pastebin.com/Tf2aCRCK

**Comment by malles** [comment]
The code looks fine, it must be a server setting. Try contacting the [gitter](https://gitter.im/aheinze/cockpit) or [G+](for some code help)

**Comment by florianletsch** [comment]
Code looks and works fine on my system. Even `var_dump($app)` doesn't print? What if you start the file with a `var_dump("hi");`?

There must be something wrong with your server config I guess

**Comment by jwhscholten** [comment]
Figured it out. Use of php shorttags was disabled on my localhost.

Thanks!
