### ISSUE TITLE
How to output collection-link's value in collection?

### ISSUE THREAD

**Issue by kamwing** [aheinze/cockpit#312]

**Comment by malles** [comment]
I don't know if it's what you mean, nor if this is THE way, but I did this:
```
				<?php foreach ($post['related'] as $related) :
					$relatedPost = collection($currentCollection)->findOne(['_id'=>$related]);
					?>
					<a href="<?php $this->route('/'. $view .'/'.$relatedPost['title_slug']);?>"><i
							class="uk-icon-link uk-margin-small-right"></i><?php echo $relatedPost['title']; ?></a>
				<?php endforeach; ?>
```

**Comment by kamwing** [comment]
Thanks @malles , but i'm using twig template engine with cockpit. Do you know how to practice this method?

**Comment by florianletsch** [comment]
If you use Lime's routing, the answer is still valid. Just make sure you have access to the `App` instance from within Twig and then call the `route` method lime @malles explained. `route` will automatically echo, which might not work with Twig, but you can should be able to use `routeUrl` instead and then output with Twig's own output functionality

**Comment by kamwing** [comment]
I use this demo in my project 
https://github.com/sitepoint-editors/cockpitdemo

**Comment by namaless** [comment]
Sorry but i need to understand what you want from collection.

In same way (php or twig) the collection is array, so you can simple extract from it, to twig is {{ collection._id }} in php is <?php echo $collection['_id'] ?>, but I think you need to undestand first the language/template engine, or examplain much better what you need :)

**Comment by florianletsch** [comment]
Then this is more of a Silex/Twig question than a Cockpit question I suppose. You should look into Silex routing and URL generation. For example at http://silex.sensiolabs.org/doc/providers/url_generator.html

**Comment by namaless** [comment]
@florianletsch if him need to create a link yes, but i think same as you, Silex question.
