### ISSUE TITLE
Mediamanager has too much ability.

### ISSUE THREAD

**Issue by ethaizone** [aheinze/cockpit#313]
My english is not good but I want to provide some test.

In media manager I can delete cockpit folder itself and I can upload new php file via mediamanager,

I don't think this is right choice. Please solve it. Thanks.

**Comment by florianletsch** [comment]
The admin account  has that access level, yes. The media manager provides the same access as having file level access. I don't think this is an issue.

For your other user accounts, you should set a media path. That way, they will only have access to said path (i.e. `/uploads` folder).
