### ISSUE TITLE
Cockpit SEO

### ISSUE THREAD

**Issue by beckybramwell** [aheinze/cockpit#315]
Hi,

Is there any way of creating meta tags for separate collections, so they can be SEO'd individually? I.E have their own meta descriptions and keywords?

Thanks,
Becky

**Comment by florianletsch** [comment]
Hey Becky. As Cockpit does not render any front-end for you, it is completely up to you how you render your HTML. Of course, you can use as many collections as you want to output whatever you see fit. So SEO isn't really anything Cockpit itself worries about.

**Comment by beckybramwell** [comment]
Thanks :)
