### ISSUE TITLE
Routing 

### ISSUE THREAD

**Issue by jwhscholten** [aheinze/cockpit#316]
Hi

I've succeeded implementing a (Lime) routing solution for my projects page based on slug, however I would also like to be able to visit my overview page without slug but I can't get this to work.

Working example route:
```php
$app->bind('/project/:slug', function($params) use($app) {
	$collection = 'Projects';
        $pagina = collection($collection)->findOne(['Titel_slug' => $params['slug']]);

        return $app->render('views/page.php', ['pagina' => $pagina, 'collection' => $collection]);
});
```
Not working:
```php
$app->bind('/project', function() use($app) {

        return $app->render('views/page.php');
        //page.php isn't empty
});

```

Any ideas on what I'm doing wrong?

**Comment by florianletsch** [comment]
I think you just need to swap the order. First bind `/project` and then bind `/project/:slug`.

**Comment by jwhscholten** [comment]
I tried it, it's not working for me. The result I'm getting is an empty page with
Index of /projects.

**Comment by malles** [comment]
Do you have the url-rewrite enable in your `.htaccess`?

**Comment by jwhscholten** [comment]
Yep, however, I fixed it by replacing the .htaccess from the cockpit blog example with the one from the Lime repo.
