### ISSUE TITLE
Assets path in css

### ISSUE THREAD

**Issue by crealx** [aheinze/cockpit#319]
Hello,
I use the assets function for my css :
 
    cockpit("cockpit")->assets(["
    css/foundation.css",
    "css/fluidbox.css",
    "css/app.css"
    ], 'my.assets' , $cachetime=0);

In my css, I have a background image : 

    .bgImg {
    background: url('../img/paint1.jpg') no-repeat center center fixed; 
    }

When I display the page, the path to the image is : /path/to/cockpit/sorage/cache/img/paint1.jpg
But all the assets of my CSS are in the root /img ... (it's the same with fonts, i.e.)

Can we specify in the css the path to this directory ??

Thank you very much !

**Comment by aheinze** [comment]
could you please try the following snippet:

```php
cockpit("cockpit")->assets([
"site:css/foundation.css",
"site:css/fluidbox.css",
"site:css/app.css"
], 'my.assets' , $cachetime=0);
```

**Comment by crealx** [comment]
Perfect ! It works fine !
Thank you
