### ISSUE TITLE
Custom Database Path Issue

### ISSUE THREAD

**Issue by Rylon** [aheinze/cockpit#328]
Hi there,

I'm trying to follow the instructions on http://getcockpit.com/docs#!getting_started/security to move the database storage to another location, but Cockpit doesn't seem to be honouring the setting.

The documentation suggests that this file needs to be created at `./custom/config.php`, but we only have that file in `./admin/custom/config.php`. Furthermore, if I create the former, and try to run Cockpit, there is no evidence that the file is executed. I tested by putting a call to `die("message here")`, which was not executed, unless I placed it in `./admin/custom/config.php`.

Is it at all possible to move the sqlite files to another path, and if so, what exactly do I need to do?

Thanks!

**Comment by thinkink** [comment]
You need to write in the 
cockpit\custom\config.php --> the following code:

<?php
if (!defined('COCKPIT_CLIENT')) define('COCKPIT_CLIENT', "newFolderStorage" );





if (!defined('COCKPIT_FOLDER_STORAGE')) define('COCKPIT_FOLDER_STORAGE',  '../client/' . COCKPIT_CLIENT );
if (!defined('COCKPIT_CUSTOM_STORAGE')) define('COCKPIT_CUSTOM_STORAGE',   COCKPIT_DIR . '/../');
if (!defined('COCKPIT_CONFIG_CLIENT_PATH')) define('COCKPIT_CONFIG_CLIENT_PATH', COCKPIT_DIR . '/../client/'. COCKPIT_CLIENT .'/config.php');
if (!defined('COCKPIT_STATICS')) define('COCKPIT_STATICS',  '../../statics/');
  
 
return array_merge([

	'i18n'     => 'ca',
	'app.name'     => '_' . COCKPIT_CLIENT,
	'database'	=> [ "server" => "mongolite://".(COCKPIT_DIR. "/" . COCKPIT_FOLDER_STORAGE . "/data"), "options" => ["db" => "cockpitdb"] ],
	'paths'        => [
                '#root'   => COCKPIT_DIR,
                'site'    => COCKPIT_DIR. "/". COCKPIT_CLIENT,
                'storage' => COCKPIT_DIR. "/" .COCKPIT_FOLDER_STORAGE.'',
                '#backups'=> COCKPIT_DIR. "/" .COCKPIT_FOLDER_STORAGE.'/backups',
                'data'    => COCKPIT_DIR. "/" .COCKPIT_FOLDER_STORAGE.'/data',
                'cache'   => COCKPIT_DIR. "/" .COCKPIT_FOLDER_STORAGE.'/cache',
                'tmp'     => COCKPIT_DIR. "/" .COCKPIT_FOLDER_STORAGE.'/cache/tmp',
                'modules' => COCKPIT_DIR.'/modules',
                'assets'  => COCKPIT_DIR.'/assets',
                'custom'  => COCKPIT_DIR.'/../custom',
                'site'    => COCKPIT_DIR == COCKPIT_DOCS_ROOT ? COCKPIT_DIR : dirname(COCKPIT_DIR)
            ],

	'debug'		=> true // enable debug mode (show errors etc.)
	], file_exists(COCKPIT_CONFIG_CLIENT_PATH) ? include(COCKPIT_CONFIG_CLIENT_PATH) : []);


_____________________________

And copy to newFolderStorage/ the current storage contents

**Comment by Rylon** [comment]
Hi there,

Thanks for your help, I set just the `database` and the `paths['data']` keys and that seems to have worked.
