### ISSUE TITLE
404 when using JS API

### ISSUE THREAD

**Issue by arthurmuchir** [aheinze/cockpit#330]
I get an error when I try to fetch my collection through JS API.
With PHP and this function, everything works fine : 
```
<?php $items = collection('articles')->find()->toArray();
```

But this doesn't work : 
```
<?php cockpit_js_lib('110e9c9296109038de9ce6ed') ?>

// In JS file : 
Cockpit.request('/collections/get/articles').success(function(items) {
	console.log(items);
});
```

Cockpit_js_lib is well loaded, but my request result is a 404.

Thanks for your help !

**Comment by krv783** [comment]
I have the exact same problem, no matter what, the token value is not passed through and it gets kicked back as a 404...?token=TOKEN never makes it through to $this->param("token", false) in file /cockpit/modules/core/RestService/bootstrap.php.. token is always blank... Any help on this would be greatly appreciated..

**Comment by krv783** [comment]
Even if I make a direct call, without JS, ny just entering the path in the address bar along with the token, I get the same result. I am trying to dynamically load some regions into a page, but i'm unsuccessful.

**Comment by krv783** [comment]
Problem solved.. Really stupid mistake.. I'm using NGINX and in my config, for "location /cockpit" was the following:

    location /cockpit {
        try_files $uri $uri /cockpit/index.php;
    }


I didn't have ARGS added...

    location /cockpit {
        try_files $uri $uri /cockpit/index.php?$args;
    }

**Comment by malles** [comment]
Happens to us all the time! Thanks for the feedback, might help others get stuck on it.
