### ISSUE TITLE
Cockpit doesn't send emails

### ISSUE THREAD

**Issue by krzksz** [aheinze/cockpit#333]
I have a weird problem with my contact form that looks like this:
```html
<?php form("Kontakt", ['class'=>'contact__form']);?>
    <input type="email" name="form[email]" class="form__input form__input--email" required placeholder="Adres email">
    <textarea name="form[message]" rows="6" class="form__input form__input--message" required placeholder="Treść wiadomości"></textarea>
    <input type="url" name="url" class="form__input form__input--url" maxlength="0">
    <input type="submit" class="form__input form__input--submit" value="Wyślij">
</form>
```
Note that `url` is a honeycomb. The problem is that I don't recieve any emails from this form although data is correctly saved when I thick this option in settings.

Are emails batched and send at certain time or is it something else?

**Comment by krzksz** [comment]
Deleted url input, now it looks like this:
```html
<?php form("Kontakt", ['class'=>'contact__form']);?>
    <input type="email" name="form[email]" class="form__input form__input--email" required placeholder="Adres email">
    <textarea name="form[message]" rows="6" class="form__input form__input--message" required placeholder="Treść wiadomości"></textarea>
    <input type="submit" class="form__input form__input--submit" value="Wyślij">
</form>
```
Alert says sending was successful, I can see messages in the admin panel but still no emails. What are the endpoints I can try to debug to pinpoint the issue?

**Comment by malles** [comment]
I'm not sure what's going wrong there. I guess debugging starts here where the form is handled:
https://github.com/aheinze/cockpit/blob/master/modules/core/Forms/bootstrap.php#L68
Which leads to the mailer, which sends the actual mail.
https://github.com/aheinze/cockpit/blob/master/vendor/Mailer.php#L18

**Comment by piotr-cz** [comment]
In PR #223 I've added mailer debug options to show what's wrong in the popup message when testing email.

Settings > Info > Send test email

**Comment by piotr-cz** [comment]
Pull request is now merged into master, you may try with [latest dev version](https://github.com/aheinze/cockpit/archive/master.zip)

powodzenia

**Comment by krzksz** [comment]
Thank you for your help, @malles's commit helped me alot!
Turns out my server had `mail()` dissabled which I noticed by calling it directly from `index.php`.

**Comment by krzksz** [comment]
Just for future use. The problem was with my hosting provider. Tested `mail()`(not working), SMTP server(working) and finally tried to send some example massage via PHPMailer(not working). This was exactly the issue: https://github.com/PHPMailer/PHPMailer/issues/368. I ended up downgrading PHP to 5.5 and problem is quite solved.
