### ISSUE TITLE
More descriptive collection view in admin panel

### ISSUE THREAD

**Issue by krzksz** [aheinze/cockpit#356]
Hey! Is there a way to set certain collection field's content to be visible in collection view in admin panel?
![capture](https://cloud.githubusercontent.com/assets/829189/9339546/fae7dc60-45ea-11e5-831e-832da3bf4394.PNG)
This is how it looks like now. What I'd like to achieve is to see the content of e.g. "title" field as a link instead of "show entry". Right now it is quite hard to tell which entry is which.

**Comment by peterbrinck** [comment]
It's very easy, just check the field you want to be shown in the panel to the right.

![screenshot from 2015-08-18 21 07 14](https://cloud.githubusercontent.com/assets/6154068/9339952/319a86d4-45ed-11e5-9c4c-cec85982f1f8.png)

**Comment by krzksz** [comment]
Wow, so simple! Thank you very much!
