### ISSUE TITLE
Find item in collection by tag

### ISSUE THREAD

**Issue by jwhscholten** [aheinze/cockpit#361]
Hi,

I would like to get collection items by tag(s).
Here's what I've tried, but this isn't working because the tags are stored in an array.

What would be the best way to achieve this?

```
$item = collection('collection')->findOne(['tags'=>'tagname']);

**Comment by jobrodesign** [comment]
Have you tried something like the following?  Not sure if this would work with the findOne method though.
```
$items = collection("collection")->find(function($item){
      return ( in_array( 'tagname', 'tags') );
    })->toArray();
```

**Comment by jwhscholten** [comment]
Thanks, got it working in my route now. Thanks!

```
    $items = collection("collection")->find(function( $slug, $item ){
      return ( in_array( $slug, $item['tags']) );
    })->toArray();
