### ISSUE TITLE
Images in region template

### ISSUE THREAD

**Issue by HelgeSverre** [aheinze/cockpit#372]
Since {{my-image}} returns ```site:img/avatar.png``` and I can't seem to use PHP code in the region template, how exactly are we supposed to use the images in region templates?

In my opinion, the result of a mediamanager field type should always return the relative path.

Any workarounds?

The documentation did not mention this.

**Comment by amdad** [comment]
Try url_to() to get relative path from it.

**Comment by HelgeSverre** [comment]
This works
```
<div class="col-lg-4 col-md-4 about-img">
  <img class="img-circle" src="{{ url_to($Avatar) }}" alt="Helge Sverre">
</div>

<div class="col-lg-8 col-md-8 about-text">
  <h3>{{ $Heading }}</h3>

  {{ $Text }}
</div>
```

This should be in the documentation.

Thanks Amdad.
