### ISSUE TITLE
PHP 7.0 Markdown (Parsedown) not working anymore

### ISSUE THREAD

**Issue by LiamMartens** [aheinze/cockpit#373]
I've upgraded my server to PHP 7.0 (I know it has only just been released but hey, don't judge me) and the Parsedown.php is giving me some issues so I believe the Markdown parser ain't woring in PHP 7.0 anymore. -> I've manually updated Parsedown to 1.6 and now it's working , so you ought to do so to

**Comment by aheinze** [comment]
thanks, done.
