### ISSUE TITLE
syntax error, unexpected '='

### ISSUE THREAD

**Issue by ViktorPontinen** [aheinze/cockpit#386]
Hello,

I have setup the folders and files exactly as in the "Simple blog example" and I get following error:

`{ "type": 4, "message": "syntax error, unexpected '='", "file": "\/storage\/content\/xxxx\/xxxx\/domain\/public_html\/views\/index.php", "line": 2 }`

Am I missing something?

**Structure:**
cockpit
views
 /  index.php
 /  article.php
.htaccess
index.php

**views/index.php**
```
<?php foreach ($posts as $post): ?>
    <h2><a href="<?php $this->route('/article/'.$post['_id']);?>"><?php=$post['title'];?></a></h2>
<?php endforeach; ?>

```

**views/article.php**
```
<h1><?php=$post['title'];?></h1>
<p>
    <?php=$post['content'];?>
</p>
```
**index.php**
```
<?php

//include cockpit
include_once('cockpit/bootstrap.php');

$app = new Lime\App();

// bind routes

$app->bind("/", function() use($app) {

    $posts = collection('blog')->find(["public"=>true])->sort(["created"=>1])->toArray();

    return $app->render('views/index.php', ['posts' => $posts]);
});


$app->bind("/article/:id", function($params) use($app) {

    $post = collection('blog')->findOne(["_id"=>$params['id']]);

    return $app->render('views/article.php', ['post' => $post]);
});

$app->run();

```

**.htaccess**
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php/$1 [QSA,L]
</IfModule>
```

In Cockpit I have created a Collection called "blog" with slug "blog" and
fields "Test" - Field label: title, "Test2" - Field label: content

Php settings:

Version: 5.6.14
PHP SAPI	: cgi-fcgi
System: Linux cry-apache-04-01 2.6.32-531.17.1.lve1.2.58.el6.x86_64 #1 SMP Wed Jun 18 08:28:56 EDT 2014 x86_64
Loaded Extensions:	Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, mcrypt, standard, mysqlnd, mysqli, mysql, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, imagick, memcache, mhash, ionCube Loader

**Comment by ViktorPontinen** [comment]
Okay,

Changed the `<?php=$post["title"] ?>` to `<?php echo $post["title"] ?>` and it works now.
I have PHP version 5.6.14, seems like the '=' syntax isn't supported for some reason and I can't find any documentation about that specific syntax. If anyone have something let me know, would be interesting to know why it ain't working.

Anyhow, closing.

**Comment by EricDupertuis** [comment]
@ViktorPontinen Here's a [thread](http://programmers.stackexchange.com/a/151694) on Stack Exchange you might find interesting.
I had a lot of problems with short tags in the past when refactoring a legacy application myself so I tend no to use them to allow for better portability of the code.

**Comment by ViktorPontinen** [comment]
@EricDupertuis Thanks for that! A bit clearer now.

I have shared hosting so my host has probably turned that option off even tho they are running PHP 5.4+. Would probably recommend to skip using short tags in example code even if application requires 5.4+.

**Comment by florianletsch** [comment]
Please replace `<?php=` with `<?=`. The first one is not a valid short tag if I'm not mistaken. 

With using _valid_ short tags, this example should work. The discussion that was linked is from 2012. In my experience, the advice not to use short tags is not valid nowaydays.

**Comment by EricDupertuis** [comment]
The `<?php=` doesn't exist (or I've never heard of it). And I still think short tags should not be used. Most shared hostings don't enable them by default (at least the one I've used) and all the dedicated server (production) I've worked with don't allow them either. 

Complete `<?php echo $var ?>`  is in my own opinion the best way.

**Comment by aheinze** [comment]
<?=$var?> is always enabed, and has nothing todo with the short tag setting

**Comment by ViktorPontinen** [comment]
Here is where `<?php=` is located:
http://getcockpit.com/docs#!tutorials/simple_blog

**Comment by aheinze** [comment]
<?php=    is wrong. I'll fix it.
