### ISSUE TITLE
Entries page doesn't list entries

### ISSUE THREAD

**Issue by gryphonmyers** [aheinze/cockpit#396]
@piotr-cz 

So I attempted to test 700b75a but it appears to have the effect of emptying the entries page:

Without new code: 
![image](https://cloud.githubusercontent.com/assets/5785304/13857487/5e531a88-ec37-11e5-9eb0-d99a6a56e504.png)

With new code:
![image](https://cloud.githubusercontent.com/assets/5785304/13857493/668325a4-ec37-11e5-861a-82749d42d6ab.png)

I don't understand the context of this code well enough to spot the error. It appears to occur when any field within the collection has an entries field other than Collection ID set.

**Comment by aheinze** [comment]
@piotr-cz could you help out please

**Comment by piotr-cz** [comment]
Please check the DevTools console output, I'd say this is a sign that there's an error when mapping collection links which prevents passing entries into view.

What do you mean by _has an entries field other than Collection ID set._?

I think I'll need exact steps to reproduce the issue.

**Comment by gryphonmyers** [comment]
Reproduction steps:

1) Create new collection with one collection link field (make sure the collection it is linking to has at least one text field and one entry to select). Make sure to tick the link field in the "Fields on entries list page:" menu. Leave the "Field on entries list page" option set to "Collection Id".
2) Create an entry for the new collection, selecting an existing entry.
3) Go to the entries page for the new collection. Observe that your entry shows up, with its collection id listed.
4) Edit the collection. Select any field other than "Collection Id" for the "Field on entries list page" option of the collection link field.
4) Go back to the entries page. Observe that there are no entries listed.
5) Edit the collection again, setting the same field's "Field on entries list page" option back to "Collection Id".
6) Go back to the entries page. Observe that the entries are now listed again, with collection IDs listed.

**Comment by piotr-cz** [comment]
When messing around with the _Field on entries list page_ setting, I've got a problem with same symptom.

The problem is that we are running `toString` method on undefined value so [this block ] should be

```js
var fieldValues = linkedEntryIds.map(function(linkedEntryId) {

    return $scope.linkedCollections[linkedCollectionId][linkedEntryId];
});
```

**Comment by gryphonmyers** [comment]
That makes the entries reappear but no value is listed on the entries page:
![image](https://cloud.githubusercontent.com/assets/5785304/13862599/a4b653cc-ec51-11e5-9de3-5aca5b3b4e83.png)

This is when I select a field called "Name" in the "Field on entries list page" option. The linked collection does have a field named "name" with a label of "Name" and a value is set for the entry I've selected.

**Comment by piotr-cz** [comment]
Cannot reproduce yet. It's late here I'll try again tomorrow.

Is your Collection link field multiple or not?
What type is linked field Name?

**Comment by gryphonmyers** [comment]
No, not multiple. "name" is a text field

![image](https://cloud.githubusercontent.com/assets/5785304/13863426/ea74d1cc-ec56-11e5-96ec-76f782878dae.png)

**Comment by gryphonmyers** [comment]
I will try reproducing from scratch with your fix applied

**Comment by gryphonmyers** [comment]
I think something in my DB or Cockpit installation might be interfering. I tried in another environment and I CAN see the name field there.

**Comment by gryphonmyers** [comment]
I should have done this sooner - the problematic environment has a console error:

![image](https://cloud.githubusercontent.com/assets/5785304/13863641/761ca2f8-ec58-11e5-9361-c742b0ac28df.png)

**Comment by gryphonmyers** [comment]
Here, "data" includes this PHP Notice:

<b>Notice</b>:  Undefined index: sortfield in <b>/var/www/html/cockpit/modules/core/Collections/Controller/Api.php</b> on line <b>117</b><br />
```

promisesBeforeLoadEntries.push(
                $http.post(App.route("/api/collections/entries"), {
                    collection: {_id: field.collection}
                })
                .success(function(data) {

                    // Create hashmap of entries, key is it's _id
                    $scope.linkedCollections[field.collection] = {};

                    data.forEach(function(entry) {

                        // Key is entry _id, value is name of entry to show instead of id
                        $scope.linkedCollections[field.collection][entry._id] = entry[field.collectionField];
                    });
                }).error(App.module.callbacks.error.http)
            );
```
Error reporting is turned off on the second server I tested so that may be why?

**Comment by piotr-cz** [comment]
Well, I told you to start with opening Developer Tools (console) and look for errors.

I'll add another commit, because in certain situations `entry[field.name]` [here](https://github.com/aheinze/cockpit/blob/master/modules/core/Collections/assets/js/entries.js#L120) is null. In my opinion it's better to check for it the beginning of the code block

**Comment by gryphonmyers** [comment]
You did! I just failed to circle back to that part of the message and
actually follow through with the suggestion ;)

**Comment by piotr-cz** [comment]
no worries, thanks for the other fix
