### ISSUE TITLE
Custom style appears not to work

### ISSUE THREAD

**Issue by webcliq** [aheinze/cockpit#407]
You will be aware that I am working on "MyCollections" as an Addon Module. I need to load module specific Javascript and CSS. 

Taking my cue from:
`-$this->helper('admin')->data['components']->append('collections:assets/field-collectionlink.tag');`
in admin.php. I added:
```
-$this->helper('admin')->data['components']->append('collections:assets/js/basket.js');
-$this->helper('admin')->data['components']->append('collections:assets/js/cliqlibraries.js');
- ......
-$this->helper('admin')->data['components']->append('collections:assets/css/jsoneditor.min.css');
```
The Helper happily loads the Tag and Js files but not the Css file. 

In \core\Cockpit\admin.php, adding a CSS file to the $assets array is acceptable. Overall, I am sure I will eventually find the solution to this (thus my earlier comment in the Community about the need for an AddOn Module template or pro-forma). Therefore in the short term and so as not to pollute/alter your standard Cockpit Next code, I put my changes in a \cockpit\config\cockpit\style.css as proposed in \cockpit\modules\core\Cockpit\admin.php at about line 113 below the definition of the $assets array. This custom style.css was **not** loaded.

**Comment by aheinze** [comment]
you can now use 

```php
$this->helper('admin')-> addAssets()
```

https://github.com/aheinze/cockpit/blob/a4672251f73ca4ea307e285db8cc3117811f5aa5/modules/core/Cockpit/Helper/Admin.php#L84-L96

**Comment by webcliq** [comment]
Implemented. Thanks.
