### ISSUE TITLE
Where to set locales in Next

### ISSUE THREAD

**Issue by zontarian** [aheinze/cockpit#410]
Hi,

I've installed the latest CockpitNext and I'm evaluating it, after a brief evaluation of the old Cockpit.
I've noticed that fields in collections can be localized also in Cockpit Next, but I don't see how to set the locales used in my site. 
The documentation refers to Cockpit older-version, since the Settings don't have a Locale tab or the like.
Anybody can help me? 

Thanks

**Comment by aheinze** [comment]
Hi,

you need to create a config file: ```config/config.yaml``` then define your additional languages like so:

```yaml
languages: [fr,de,en]
```

Greets,
Artur

**Comment by zontarian** [comment]
Thanks, it works!
Can be done from interface via Settings / Settings (editing the YAML file on line)

**Comment by aheinze** [comment]
👍🏻

**Comment by zontarian** [comment]
Just an afterthought, can we get rid of the "default" language, or your suggestion is to use the default as the main language of the site?
As an example, I plan to write my site (btw, to be staticized with Hugo or Jekyll) in English and Italian. 
In the `config.yaml` file I've put `languages: [it,en]` and now when I edit an entry in a Collection, if the field is localizable,  I have the choice between "default", "italian" and "english". 
Is there a way to make one of the two language the "default", or the solution is maybe to specify:

`languages: [en]` and simply treat Italian as the default language (I'm italian as you may have guessed)

Thanks

**Comment by aheinze** [comment]
right, default should be your primary language.

**Comment by zontarian** [comment]
Ok, makes kinda sense. Really closed now :)
