### ISSUE TITLE
Redirects back to login screen after successful login

### ISSUE THREAD

**Issue by Mattnmoore** [aheinze/cockpit#415]
Hitting my base URI correctly redirects me to `/auth/login` but after I enter the credentials and login, it just reloads the same page.

**Comment by Mattnmoore** [comment]
My sessions did not have the correct permissions. Resolving that fixed the issue.

**Comment by srpf** [comment]
I have this same problem. 
Help me please. 🆘

**Comment by srpf** [comment]
> My sessions did not have the correct permissions. Resolving that fixed the issue.
@Mattnmoore How do you fix this problem?
