### ISSUE TITLE
Add docs on creating addons

### ISSUE THREAD

**Issue by supernovagurl** [aheinze/cockpit#6]
Really love this! Perhaps creating docs on how to create an addon?

**Comment by Daandelange** [comment]
SitePoint also published [an introduction to Cockpit CMS](http://www.sitepoint.com/introducing-cockpitcms-cms-developers/) which is quite a useful ressource.
_(Googling Cockpit developper issues is quite a pain in the ass...)_

**Comment by alioygur** [comment]
is there a documentation?

**Comment by xJoeyv** [comment]
Yea wondering to. I want to intergate 2 things into my cockpit.

**Comment by G-Rath** [comment]
@StevenDevooght I tried out your repo (which looks really cool), but sadly Cockpit didn't seem to like it.

I've created [an issue](https://github.com/StevenDevooght/cockpit-todos/issues/3) on the repo 😄
